numpy

In [5]:
import numpy as np

In [8]:
arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [9]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5)

array([[1, 2, 3, 4, 5]])

In [12]:
arr3 = np.array([[1,2,3,4,5],[2,3,4,5,6]])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [14]:
np.arange(0,10,2).reshape(5,1
                          )

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [19]:
#numpy vectorized opearation
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([10,20,30,40,50])

print("addtion = ",arr1 + arr2)
print("subtraction = ",arr2 - arr1);
print("multiplication",arr1 * arr2)

addtion =  [11 22 33 44 55]
subtraction =  [ 9 18 27 36 45]
multiplication [ 10  40  90 160 250]


In [21]:
#universal function
arr = np.array([2,3,4,5,6])
print(np.sqrt(arr))
print(np.sin(arr))
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [33]:
#array slicing and indexing
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("array = \n", arr)
print("slicing = \n")
print(arr[1:,2:])
print("slicing = \n")
print(arr[:2,2:])
print("slicing = \n")
print(arr[1:,1:3])

array = 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
slicing = 

[[ 7  8]
 [11 12]]
slicing = 

[[3 4]
 [7 8]]
slicing = 

[[ 6  7]
 [10 11]]


In [36]:
#modify arr elements
arr[0][0] = 100;
print(arr)
print("updation")
arr[1:] = 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]
updation
[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [39]:
##statistical concepts -- normalization
#to have a mean of 0 and stadard deviation of 1;
mean = np.mean(arr)
print(mean)
std = np.std(arr);
print(std)

75.75
42.00421605823238


In [41]:
mean = np.mean(arr)
median = np.median(arr)
print(mean)
print(median)

75.75
100.0


In [45]:
##logical operation
data = np.array([1,2,3,4,5,6,7,8,9])
data[data>5]

array([6, 7, 8, 9])