**numpy tutorial

In [43]:
import numpy as np

In [44]:
myarr = np.array([1,2,3,4,5])
print(myarr)
print(myarr[3])
print(myarr.shape)
print(myarr.dtype)

[1 2 3 4 5]
4
(5,)
int64


In [45]:
myarr = np.array([[1,2,3,4,5]])
print(myarr)
print(myarr[0][2])
print(myarr.shape)
print(myarr.dtype)
myarr[0][2] = 45
print(myarr[0][2])

[[1 2 3 4 5]]
3
(1, 5)
int64
45


array creation : conversion from other python sturctures  

In [46]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(listarray)
print(listarray.shape)
print(listarray.dtype)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64


In [47]:
newarr = np.zeros((2,5))
print(newarr)
print(newarr.dtype)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
float64


In [48]:
rng = np.arange(10,20)
print(rng)

[10 11 12 13 14 15 16 17 18 19]


In [49]:
ls = np.linspace(1,5,5)
print(ls)

[1. 2. 3. 4. 5.]


In [50]:
emp = np.empty((2,4))
print(emp)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [51]:
emp_like = np.empty_like(ls)
print(emp_like)

[1. 2. 3. 4. 5.]


In [52]:
arr = np.identity(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


array reshaping

In [53]:
arr = np.arange(99)
print(arr)
arr = arr.reshape(3,33)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98]


In [54]:
print(arr)
arr.ravel()

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24 25 26 27 28 29 30 31 32]
 [33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56
  57 58 59 60 61 62 63 64 65]
 [66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89
  90 91 92 93 94 95 96 97 98]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

axis tutorial

In [55]:
arrr = [[1,2,3],[4,5,6],[7,8,9]]
arrr = np.array(arrr)
print(arrr)
print("sum around axis is  -")
print(arrr.sum(axis=0))
print(arrr.sum(axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
sum around axis is  -
[12 15 18]
[ 6 15 24]


ATTRIBUTE AND METHODS

In [58]:
arrr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [60]:
omfo = arrr.flat
for items in omfo:
    print(items)


1
2
3
4
5
6
7
8
9


In [62]:
arrr.ndim

2

In [63]:
arrr.size

9

In [64]:
arrr.nbytes

72

In [70]:
print(arrr.argmax())
print(arrr.argmax(axis=0))
print(arrr.argmin())
print(arrr.argmin(axis=1))
print("sorted array is  : -")
print(arrr.argsort())

8
[2 2 2]
0
[0 0 0]
sorted array is  : -
[[0 1 2]
 [0 1 2]
 [0 1 2]]


MATHEMATICAL OPERATIONS

In [74]:
ar1 = np.array([[1,2,3],[1,2,3],[1,2,3]])
ar2 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [77]:
print("addition :-")
print(ar1+ar2)
print("multiplication :-")
print(ar1*ar2)
print("these operation can be done addition, subtraction, multiplication, division, exponentiation, modulus")

addition :-
[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]
multiplication :-
[[ 1  4  9]
 [ 4 10 18]
 [ 7 16 27]]
these operation can be done addition, subtraction, multiplication, division, exponentiation, modulus


In [81]:
print(np.sqrt(ar1))

[[1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]
 [1.         1.41421356 1.73205081]]


In [ ]:
print(ar1.sum())
print(ar1.max())
print(ar1.min())
print(np.where(ar2>5))
print(np.count_nonzero(ar1)) #no where 0 is not 
print(np.nonzero((ar1))) #gives coordinates where 0 is not 

18
3
1
(array([1, 2, 2, 2]), array([2, 0, 1, 2]))
9
(array([0, 0, 0, 1, 1, 1, 2, 2, 2]), array([0, 1, 2, 0, 1, 2, 0, 1, 2]))
